---
deployment:
      tasks:
        - export DEPLOYPATH=/mnt/volume-fra1-01/mokhtarali/public_html/portfolio/qoot
        - script: npm install
        - script: npm run gulp
        - /bin/rm -Rf $DEPLOYPATH/src
        - /bin cp * $DEPLOYPATH                           #copy all from root